### ISSUE TITLE
官方在开发这个版本时，nacos连接的数据库是mysql还是Oracle？

### ISSUE THREAD

**Issue by 1776894091** [yangzongzhuan/RuoYi-Cloud-Oracle#4]
请问一下，官方在开发这个版本时，nacos连接的数据库是mysql还是Oracle？如果是Oracle能否把这个改过的nacos提供一下？

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
