### ISSUE TITLE
执行oralce初始化脚本出错了

### ISSUE THREAD

**Issue by qi20099** [yangzongzhuan/RuoYi-Cloud-Oracle#5]
![image](https://user-images.githubusercontent.com/107980459/232032296-15a1047d-b1ec-4244-b6ec-9f3e2edaa66d.png)
使用的oracle版本是12C。

报错信息如下：
SQL 错误 [6550] [65000]: ORA-06550: 第 2 行, 第 36 列: 
PL/SQL: ORA-00904: "ARG1": 标识符无效
ORA-06550: 第 2 行, 第 1 列: 
PL/SQL: SQL Statement ignored
ORA-06550: 第 3 行, 第 1 列: 
PLS-00372: 在一个过程中, RETURN 语句无法包含表达式
ORA-06550: 第 3 行, 第 1 列: 
PL/SQL: Statement ignored

  Error : 6550, Position : 42, Sql = begin
select instr(','||arg2||',' , ','||arg1||',') into Result from dual;
return(Result);
end find_in_set;, OriginalSql = begin
select instr(','||arg2||',' , ','||arg1||',') into Result from dual;
return(Result);
end find_in_set;, Error Msg = ORA-06550: 第 2 行, 第 36 列: 
PL/SQL: ORA-00904: "ARG1": 标识符无效
ORA-06550: 第 2 行, 第 1 列: 
PL/SQL: SQL Statement ignored
ORA-06550: 第 3 行, 第 1 列: 
PLS-00372: 在一个过程中, RETURN 语句无法包含表达式
ORA-06550: 第 3 行, 第 1 列: 
PL/SQL: Statement ignored

  ORA-06550: 第 2 行, 第 36 列: 
PL/SQL: ORA-00904: "ARG1": 标识符无效
ORA-06550: 第 2 行, 第 1 列: 
PL/SQL: SQL Statement ignored
ORA-06550: 第 3 行, 第 1 列: 
PLS-00372: 在一个过程中, RETURN 语句无法包含表达式
ORA-06550: 第 3 行, 第 1 列: 
PL/SQL: Statement ignored

**Comment by qi20099** [comment]
我修改了下：
CREATE OR REPLACE FUNCTION find_in_set(arg1 IN VARCHAR2, arg2 IN VARCHAR2)
RETURN NUMBER IS
  Result NUMBER;
BEGIN
  SELECT INSTR(',' || arg2 || ',', ',' || arg1 || ',') INTO Result FROM dual;
  RETURN Result;
END find_in_set;
/

可以执行成功了。

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
