### ISSUE TITLE
发现这个sql非oracle的脚本哦。是mysql的。

### ISSUE THREAD

**Issue by qi20099** [yangzongzhuan/RuoYi-Cloud-Oracle#6]
![image](https://user-images.githubusercontent.com/107980459/232035715-c2807e39-c7dd-4292-88d1-0cbed610d688.png)
发现这个sql非oracle的脚本哦。是mysql的。麻烦更新下oracle版本的

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
